<?php
// SE JÁ ESTÁ DEFINIDO O GAME
	// SE JÁ VOTOU NO GAME => RESULT.PHP
	// SE NÃO VOTOU NO GAME
		// SE JÁ ESTÁ DEFINIDO O FRIEND => PROFILE.PHP
		// SE NÃO ESTÁ DEFINIDO O FRIEND
			// SE TEM AMIGOS CADASTRADOS => CHOOSE_FRIEND.PHP => PROFILE.PHP
			// SE NÃO TEM AMIGOS CADASTRADOS => CHOOSE_GAME.PHP => PROFILE.PHP
// SE NÃO ESTÁ DEFINIDO O GAME
	// SE TEM AMIGOS CADASTRADOS => CHOOSE_FRIEND.PHP
		// SE JÁ VOTOU NO GAME => RESULT.PHP
		// SE NÃO VOTOU NO GAME => PROFILE.PHP
	// SE NÃO TEM AMIGOS CADASTRADOS => CHOOSE_GAME.PHP => PROFILE.PHP